_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": epoch
              "6":
                - 3
              "7": []
            - "1": step
              "6":
                - 3
              "7": []
            - "1": loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": curvature_strength
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": metric_determinant
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.0
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
                - 23
                - 55
                - 62
            "4": 3.12.0
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
dimensions:
    value: 4
steps_per_epoch:
    value: 8
total_epochs:
    value: 30
total_steps:
    value: 240
update_interval:
    value: 0.2
