_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.0
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 16
checkpoint_interval:
    value: 5
data_type:
    value: sphere
device:
    value: null
embedding_dim:
    value: 5
input_dim:
    value: 55
learning_rate:
    value: 0.001
num_epochs:
    value: 30
num_samples:
    value: 1000
save_dir:
    value: ./results
use_wandb:
    value: true
visualization_interval:
    value: 10
wandb_project:
    value: manifold-deep-learning
wandb_run_name:
    value: manifold-learning-20250317-140611
weight_decay:
    value: 1e-05
